In [2]:
import numpy as np

In [16]:
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)
print(arr1.dtype)
print(arr1.ndim)
print(arr1.size)
print(arr1.itemsize)
print(arr1.nbytes)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
int64
1
5
8
40


In [19]:
arr2 = np.array([1, 2, 3, 4, 5]}
arr2.reshape(1,5)# Reshape to 1 row and 5 columns
print(arr2)


[1 2 3 4 5]


In [25]:
arr2=np.array([1,2,3,4,5])
arr3=np.array([6,7,8,9,10])
arr4=np.concatenate((arr2,arr3))
print(arr2+arr3)
print(arr2*arr3)
print(arr4)
print(type(arr4))

[ 7  9 11 13 15]
[ 6 14 24 36 50]
[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [27]:
## universal functions
arr1 = np.array([1, 2, 3, 4, 5])
print(np.sqrt(arr1)) ## Square root
print(np.exp(arr1)) ## Exponential
print(np.log(arr1)) ## Natural logarithm
print(np.sin(arr1)) ## Sine
print(np.cos(arr1))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [40]:
##array slicing indexing
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2[0, 1])
## Slicing three dimensional array
arr3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr3)
print("Accessing a specific element:")  
print(arr3[1])  # Slicing rows and columns
print("coment ")  # Accessing a specific element
print(arr3[1:3])  # Accessing a specific element

2
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Accessing a specific element:
[5 6 7 8]
coment 
[[ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
## modifying array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2[0, 1] = 10     # Modifying a specific element                  
print(arr2)


[[ 1 10  3]
 [ 4  5  6]]


In [ ]:
### stastical concept normalization
## to have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5])
#calculate mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)
# Normalize the data
normalized_data = (data - mean) / std_dev
print("Original Data:", data)
print("Mean:", mean)
print("Standard Deviation:", std_dev)
print("Normalized Data:", normalized_data)




Original Data: [1 2 3 4 5]
Mean: 3.0
Standard Deviation: 1.4142135623730951
Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [44]:
data = np.array([1, 2, 3, 4, 5,6,7,8,9,10])
# Calculate the mean and standard deviation
mean = np.mean(data)
print("Mean:", mean)
# Median
median = np.median(data)
print("Median:", median)
# Standard deviation        
print("Standard Deviation:", np.std(data))
std_dev = np.std(data)
# Variance
variance = np.var(data)
print("Variance:", variance)    

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [55]:
## logical operations
arr1 = np.array([1, 2, 3, 4, 5,6,7,8,9,10])
arr1>3# Logical operation to check if elements are greater than 3   
arr1[arr1 > 3]  # Filtering elements greater than 3
arr1[(arr1 < 5) & (arr1 > 2)]  # Filtering elements less than 5 and 4
arr1[(arr1 < 5) | (arr1 > 8)]  # Filtering elements less than 5 or greater than 8

array([ 1,  2,  3,  4,  9, 10])

In [3]:
# Create a 5x5 array filled with random integers between 1 and 20
arr = np.random.randint(1, 21, size=(5, 5))

# Replace all elements in the third column (index 2) with 1
arr[:, 2] = 1

print(arr)


[[ 8  5  1 18  7]
 [11  1  1 15 13]
 [18 10  1  8 11]
 [ 7  3  1 11 14]
 [ 4  6  1  1 11]]
